import os, dotenv
dotenv.load_dotenv()

MICROSOFT_APP_CLIENT_ID = os.getenv("MICROSOFT_APP_CLIENT_ID")
MICROSOFT_APP_SECRET = os.getenv("MICROSOFT_APP_SECRET")

EVENTS_PARSER_MYSQL_USER = "events_parser"
EVENTS_PARSER_MYSQL_PASSWORD = os.getenv("EVENTS_PARSER_MYSQL_PASSWORD")

SCOPES=["Mail.ReadBasic", "Mail.Read"]


SESSION_TYPE = "SESSION_MONGODB"
SESSION_MONGODB_HOST = "172.17.89.147:27017"
SESSION_MONGODB_FLASK_USER = "flask"
SESSION_MONGODB_FLASK_PASSWORD = os.getenv("MONGODB_FLASK_PASSWORD")
SESSION_MONGODB_FLASK_DB = "flask_session"

MODEL_FILE = "./gemma/gemma-2-9b-it-Q8_0-f16.gguf"