import os, dotenv
dotenv.load_dotenv()

MICROSOFT_APP_CLIENT_ID = os.getenv("MICROSOFT_APP_CLIENT_ID")
MICROSOFT_APP_SECRET = os.getenv("MICROSOFT_APP_SECRET")
MICROSOFT_LOGIN_REDIRECT = "http://localhost:5000/finishLogin"

SCOPES=["Mail.ReadBasic", "Mail.Read"]

SESSION_TYPE = "mongodb"
SESSION_MONGODB_HOST = "172.17.89.147"
SESSION_MONGODB_FLASK_USER = "flask"
SESSION_MONGODB_FLASK_PASSWORD = os.getenv("MONGODB_FLASK_PASSWORD")
SESSION_MONGODB_FLASK_DB = "events_flask_sessions"